dj_16/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from inventory import views

from django.views.i18n import javascript_catalog
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import activate

from inventory.models import Item
# from rest_framework import routers, serializers, viewsets
# from rest_framework import routers

admin.autodiscover()

js_info_dict = {
    'packages': ('inventory',),
}


# Serializers define the API representation.
# class ItemSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = Item
#         fields = ('url', 'title', 'description', 'amount')

# ViewSets define the view behavior.
# class ItemViewSet(viewsets.ModelViewSet):
#     queryset = Item.objects.all()
#     serializer_class = ItemSerializer

# Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router = routers.SimpleRouter()
# router.register(r'items', ItemViewSet)

from inventory.views import HomePageView
from inventory.views import MyView
from inventory.dispatch_view import dispatch_view

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dj_16.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Class-based-views
    url(r'^home/', HomePageView.as_view(), name='home'),
    url(r'^about/', MyView.as_view()),
    # url(r'^about2/', MyView()),
    url(r'^about2/', dispatch_view(MyView()), name='About2'),
    url(r'^$', dispatch_view(views.index), name='index'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^item/(?P<id>\d+)/',views.item_detail, name='item_detail'),
    url(r'^test/', include('inventory.urls')),
    url(r'^item_add/', views.item_add, name='item_add'),
    url(r'^item_add2/', views.item_add2, name='item_add2'),
    url(r'^clean_email/', views.clean_email, name='clean_email'),
    
    url(r'^save_item', views.save_item, name='save'),
    url(r'^thanks/', views.thanks, name='thanks'),
    url(r'^parser/', views.parser, name='parser'),
    url(r'^parsing/', views.parsing, name='parsing'),
    url(r'^scan/', views.scan, name='scan'),
    url(r'^scan_opp/', views.scan_opp, name='scan_opp'),
    # url(r'^list_from_xlsx/', views.list_from_xlsx, name='list_from_xlsx'),
    url(r'^list_from_html/', views.list_from_html, name='list_from_html'),

    url(r'^authen/', views.authen, name='authen'),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'inventory/login.html'}),
    url(r'^accounts/profile/', views.profile_see, name='profile_see'),
    url(r'^accounts/check_login/', views.check_login, name='check_login'),
    # url(r'^my_view/(?P<m>\d+)/(?P<d>\d+)/', views.my_view, name='my_view'),
    # (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    # url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^test_ajax/', views.test_ajax, name='test_ajax'),
    url(r'^ajax_json/', views.ajax_json, name='ajax_json'),
    url(r'^test_try/(?P<x>\d+)/', views.test_try, name='test_try'),
    url(r'^test_try2/(?P<x>\d+)/', views.test_try2, name='test_try2')
    )

# urlpatterns += router.urls

urlpatterns += i18n_patterns('',
    # url(r'^about/$', 'about.view', name='about'),
    url(r'^my_view/', views.my_view, name='my_view'),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
)

inventory/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index2, name='index23'),
]

inventory/models.py
from __future__ import unicode_literals

from django.db import models
from .validators import validate_description

from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Item(models.Model):
    title = models.CharField(max_length=200)
    # title = models.CharField(max_length=200,help_text=pgettext_lazy('help text for MyThing model', 'This is the help text'))
    description = models.TextField()
    # description = models.TextField(_('description !'),help_text=_('This is the help text'))
    amount = models.IntegerField(max_length=6)
    field4 = models.TextField(null=True, blank=True)
    field5 = models.TextField(default="default_5")
    SIZE = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
    )
    field7 = models.CharField(max_length=2, choices=SIZE, default='X')

    def _get_full_name(self): # The last method in this example is a property.
        "Returns the person's full name."
        return 'Get_full_name title::%s description::%s' % (self.title, self.description)
    full_name = property(_get_full_name)

    def __unicode__(self):
        return self.title

class Knight(models.Model):
    name = models.CharField(max_length=100)
    of_the_round_table = models.BooleanField()
    old = models.IntegerField(null=True)
    def __unicode__(self):
        return self.name
class Employee(models.Model):
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True 
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


class Person(models.Model):
    name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def baby_boomer_status(self):
        "Returns the person's baby-boomer status."
        import datetime
        if self.birth_date < datetime.date(1945, 8, 1):
            return "Pre-boomer"
        elif self.birth_date < datetime.date(1965, 1, 1):
            return "Baby boomer"
        else:
            return "Post-boomer"

    def _get_full_name(self): # The last method in this example is a property.
        "Returns the person's full name."
        return '%s %s' % (self.first_name, self.last_name)
    full_name = property(_get_full_name)
    def __unicode__(self):
        return self.name

class Group(models.Model):
    name = models.CharField(max_length=128)
    members = models.ManyToManyField(Person, through='Membership')
    def __unicode__(self):
        return self.name

class Membership(models.Model):
    person = models.ForeignKey(Person)
    group = models.ForeignKey(Group)
    date_joined = models.DateField()
    invite_reason = models.CharField(max_length=64)

inventory/forms.py
from django import forms
from django.contrib import admin
from inventory.models import Item
from inventory.models import Knight
from django.core.exceptions import ValidationError
from .validators import validate_description

# class ItemForm(forms.Form):
class ItemForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        # Call the original __init__ method before assigning
        # field overloads
        super(ItemForm, self).__init__(*args,**kwargs)
        self.fields["title"].required = False
        self.fields["description"].required = True
        self.fields["description"].validators.append(validate_description)

    
    class Meta:
        model = Item
        fields = ['title', 'description', 'amount', 'field4', 'field7']
    
    # ... Don't do this! Duplication of the model field!
    # amount = forms.CharField()
    field4_select = forms.ModelChoiceField(queryset=Knight.objects.all(), empty_label="--",to_field_name="name")
    
    def clean(self):
        cleaned_data = super(ItemForm, self).clean()
        data_title = cleaned_data.get("title", "")
        if (data_title == '1'):
            raise forms.ValidationError("_Title invalid.")
        return cleaned_data

    def clean_amount(self):
        # do something that validates your data
        data_amount = self.cleaned_data['amount'] 
        # khi validate mac dinh qua, no moi xuong day valid lan nua
        if data_amount > 10:
            raise forms.ValidationError("_You must input < 10")
        return data_amount

class ItemAdmin(admin.ModelAdmin):
    exclude = ['title']
    form = ItemForm

class UploadFileForm(forms.Form):
    parse_file  = forms.FileField()

class ForgotPassForm(forms.Form):
    email = forms.EmailField(max_length=16, required=True, 
        widget=forms.TextInput(attrs={'placeholder':'Email','class': 'input-block-level'}), 
            error_messages={'required': 'Please input a email'}
                )
    
    # rating = forms.ChoiceField(choices=STARS, error_messages={'required': 'Please choose a star rating'})
    #def clean(self):
    #    print "==>clean", form_data.get('email') #['email']
    #    form_data = self.cleaned_data
    #    if form_data['email'] == '':
    #        raise forms.ValidationError("111!")
    #    return form_data
    # class Meta:
    #     error_messages = {
    #         'email': {
    #             'required': "Please input",
    #         },
    #     }
    def clean(self):
        cleaned_data = super(ForgotPassForm, self).clean()
        email = cleaned_data.get("email")
        if email:
            if "VV" not in email:
                raise forms.ValidationError("Phai co VV")
        # print "-----------",form_data.get('email')
        # return form_data
    # def clean_email(self):
    #     print "==>clean email"
    #     data_email = self.cleaned_data['email'] # 212@gm.com
    #     # khi validate mac dinh qua, no moi xuong day valid lan nua
    #     #if data_email != ' ':
    #     #    raise forms.ValidationError("You must input email")
    #     if "fred@example.com" not in data_email:
    #         # raise forms.ValidationError('email not exist', code='invalid')
    #         raise forms.ValidationError("You have forgotten about Fred!")
    #     return data_email

templates/inventory/clean_email.html
{% extends "base.html" %}

{% block content %}
    <p>Clean email</p>

    <form action="/clean_email/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="submit" value="Submit" />
    </form>

    <a href="{% url 'index' %}">Home</a>
{% endblock %}

templates/inventory/index.html
{% extends "base.html" %}
{% block content %}
    <h3>Items in Stock</h3>
    <ul>
        {% for item in items %}
        <li>
            <a href="{% url 'item_detail' item.id %}">
                {{ item.title|capfirst }}
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/inventory/item_add.html
{% extends "base.html" %}

{% block content %}
    <p>Add Item</p>

    <form action="/contact/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="submit" value="Submit" />
    </form>

    <a href="{% url 'index' %}">Home</a>



<!-- <p>
<label for="id_subject">Subject:</label> <input id="id_subject" maxlength="100" name="subject" type="text" />
</p>
<label for="id_message">Message:</label> 
<input id="id_message" name="message" type="text" />
<label for="id_sender">Sender:</label> 
<input id="id_sender" name="sender" type="email" />
<label for="id_cc_myself">Cc myself:</label> 
<input id="id_cc_myself" name="cc_myself" type="checkbox" />
<input type="submit" value="Submit" /> -->


{% endblock %}
    
{% block javascript %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'main.js' %}"></script>
{% endblock %}

templates/inventory/item_add2.html
{% extends "base.html" %}

{% block content %}
    <p>Add Item</p>
    <form action="/item_add2/" method="post">
    {% csrf_token %}
    <p>
    	<label for="id_title">Title:</label>
    	{{ form.title }}
    	{{ form.title.errors }}
        {{ form.non_field_errors }}
    </p>
    <p>
    	<label for="id_description">Description:</label>
    	{{ form.description }}
    	{{ form.description.errors }}
    </p>	
	<p>
		<label for="id_amount">Amount:</label>
		{{ form.amount }}
    	{{ form.amount.errors }}
	</p>
    <p>
        <label for="id_field4_select">Field 4 Select:</label>
        {{ form.field4_select }}
        {{ form.field4_select.errors }}
    </p>
    <p>
        <label for="id_field7">Field7:</label>
        {{ form.field7 }}
        {{ form.field7.errors }}
    </p>
    <input type="submit" id="submit" value="Submit" />
    </form>


    <a href="{% url 'index' %}">Home</a>
{% endblock %}

templates/inventory/item_detail.html
{% extends "base.html" %}

{% block content %}
    <p>item detail page</p>
    <h3>{{ item.title|capfirst }}</h3>
    <p>{{ item.amount }} currently in stock</p>
    <h4>Description:</h4>
    <p>{{ item.description }}</p>

    <h4>Get_full_name:</h4>
    <p>{{ item.full_name }}</p>

    <a href="{% url 'index' %}">Home</a>
{% endblock %}

templates/inventory/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/inventory/my_view.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <script type="text/javascript" src="{% url 'django.views.i18n.javascript_catalog' %}"></script>
</head>
<body>
  <p>{{ page }}, {% trans 'let take a look on my website' %}</p>
  <p><a onclick="alert(gettext('let take a look on my website'))" href="#">{% trans 'Say hello' %}</a></p>

  {% get_available_languages as languages %}

  {% trans "View this page in:" %}
  {% for lang_code, lang_name in languages %}
      {% language lang_code %}
      <a href="{% url 'my_view'  %}">{{ lang_name }}</a>
      {% endlanguage %}
  {% endfor %}
</body>
</html>

templates/inventory/parser.html
{% extends "base.html" %}
{% block content %}
    <h3>Parser</h3>
    <form enctype="multipart/form-data" action="/parsing/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="submit" value="Upload" />
    </form>
{% endblock content %}

templates/inventory/parsing.html
{% extends "base.html" %}
{% block content %}
    <h3>Parser JSON</h3>
    <h3>{{ dic }}</h3>
{% endblock content %}

templates/inventory/profile_see.html
{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}

templates/inventory/test_ajax.html
{% extends "base.html" %}

{% block content %}
    <p>Test Ajax</p>

    <a href="{% url 'index' %}">Home</a>
{% endblock %}
    
{% block javascript %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'test_ajax.js' %}"></script>
{% endblock %}

templates/inventory/thanks.html
<h1> thanks, Uploaded </h1>
<h3>{{ ip }}</h3>